### ISSUE TITLE
Package 'animalTrack' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/SpatioTemporal#19]
Package [animalTrack](https://CRAN.R-project.org/package=animalTrack) is currently listed in CRAN Task View [SpatioTemporal](https://CRAN.R-project.org/view=SpatioTemporal) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
This project seems to be dead so that removed from the task view seems to be appropriate now.

FYI: Mathieu @basille (from the Tracking task view maintainers) has reached out to the authors and there was no follow-up despite only simple changes being necessary: https://github.com/EdFarrell/animalTrack/issues/2
